export const cryptos = [
  { value: "bitcoin", label: "Bitcoin" },
  { value: "ethereum", label: "Ethereum" },
  { value: "tether", label: "Tether" },
  { value: "cardano", label: "Cardano" },
  { value: "dogecoin", label: "Dogecoin" },
  { value: "xrp", label: "XRP" },
  { value: "usd-coin", label: "USD Coin" },
  { value: "polkadot", label: "Polkadot" },
  { value: "binance-usd", label: "Binance USD" },
  { value: "uniswap", label: "Uniswap" },
  { value: "chainlink", label: "Chainlink" },
  { value: "litecoin", label: "Litecoin" },
  { value: "bitcoin-cash", label: "Bitcoin Cash" },
  { value: "stellar", label: "Stellar" },
  { value: "solana", label: "Solana" },
  { value: "matic-network", label: "Polygon" },
  { value: "vechain", label: "VeChain" },
  { value: "theta-token", label: "Theta Token" },
  { value: "filecoin", label: "Filecoin" },
  { value: "tron", label: "TRON" },
  { value: "cosmos", label: "Cosmos" },
  { value: "terra-luna", label: "Terra" },
  { value: "avalanche-2", label: "Avalanche" },
  { value: "tezos", label: "Tezos" },
  { value: "eos", label: "EOS" },
  { value: "neo", label: "NEO" },
  { value: "algorand", label: "Algorand" },
  { value: "compound-ether", label: "Compound Ether" },
  { value: "maker", label: "Maker" },
  { value: "compound-usd-coin", label: "Compound USD Coin" },
  { value: "compound-governance-token", label: "Compound Governance Token" },
  { value: "aave", label: "Aave" },
  { value: "sushi", label: "SushiSwap" },
  { value: "yearn-finance", label: "yearn.finance" },
  { value: "pancakeswap-token", label: "PancakeSwap" },
  { value: "binance-coin", label: "Binance Coin" },
  { value: "huobi-token", label: "Huobi Token" },
  { value: "ftx-token", label: "FTX Token" },
  { value: "terrausd", label: "TerraUSD" },
  { value: "bitcoin-cash-sv", label: "Bitcoin SV" },
  { value: "dash", label: "Dash" },
  { value: "zcash", label: "Zcash" },
  { value: "monero", label: "Monero" },
  { value: "ethereum-classic", label: "Ethereum Classic" },
  { value: "digibyte", label: "DigiByte" },
  { value: "ravencoin", label: "Ravencoin" },
  { value: "zilliqa", label: "Zilliqa" },
  { value: "ontology", label: "Ontology" },
  { value: "icon", label: "ICON" },
  { value: "qtum", label: "Qtum" },
];
