import Providers from '@/components/Provider'
import './globals.css'
import Header from '@/components/Header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className='bg-slate-300 dark:bg-zinc-700 transition-all duration-700'>
					<Header />
					<div>{children}</div>
          </div>
				</Providers>
      </body>
    </html>
  )
}
