import Theme from "@/components/layouts/Theme";
import "./globals.css";
import Header from "@/components/layouts/Header";

export const metadata = {
  title: "MINI-DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <div className="bg-slate-300 dark:bg-zinc-700 transition-all duration-700">
            <Header />
            <div>{children}</div>
          </div>
          <footer className="text-center text-gray-500 text-sm py-4">
            &copy; {new Date().getFullYear()} MINI DASHBOARD - THE BIG COMPANY
            🚀
          </footer>
        </Theme>
      </body>
    </html>
  );
}
